### ISSUE TITLE
content.text should never be `null`

### ISSUE THREAD

**Issue by kennethklee** [Mashape/analytics-agent-nodejs#11]
Agent always sends request.content.text and response.content.text. They should be omitted if text doesn't exist.

**Comment by ahmadnassri** [comment]
no, this is wrong. current behaviour is correct.

**Comment by SGrondin** [comment]
As discussed with Ahmad previously, this is how it works:

- If replays on the agent/proxy are enabled, there must be a Content object.
- If there is a Content object, the text field must be set.
- In case of an empty body, the text field will contain an empty string.

There is never any null. ever. ever. ever.

ever.

**Comment by kennethklee** [comment]
Just discussed with Ahmad. Null means the agent failed to process the body.

**Comment by SGrondin** [comment]
I don't understand how it could fail to base64-encode a string in the first place, but ok. It just seems like a hack to me.
